### ISSUE TITLE
Docker-compose not working on buster

### ISSUE THREAD

**Issue by Duvel** [hypriot/image-builder-rpi#308] opened 2019-08-08 17:20 UTC
I already found this with raspbian buster, but running docker-compose on hypriot 1.11 gives also the following error:

ImportError: No module named ssl_match_hostname

I found a solution here: https://github.com/docker/docker-py/issues/1502#issuecomment-506544849.

After doing it works for me:
```
sudo pip uninstall backports.ssl-match-hostname
sudo apt install python-backports.ssl-match-hostname
```

**Comment by StefanScherer** [comment] 2019-09-08 10:05
I cannot reproduce the problem. Can you share more details, eg. which docker-compose commands you called or the docker-compose.yml that you are using?

**Comment by Duvel** [comment] 2019-09-08 10:49
I think it has been resolved now in buster itself and this is no longer needed. I already noticed in a flash this week or so, that it was no longer necessary.

**Comment by GabeBigBoxVR** [comment] 2019-12-03 01:58
This is still happening to me on a fresh buster install on pi4.

**Comment by Duvel** [comment] 2019-12-18 18:06
On a fresh install this isn't an issue, but when you install pip this package apparently get's installed and then breaks docker-compose.

Maybe an idea to switch to python 3 to solve this problem.

**Comment by StefanScherer** [comment] 2020-01-05 17:56
Thanks @Duvel for the update. Yes, it's time to switch to python3.

**Comment by StefanScherer** [comment] 2020-01-05 21:07
Should be fixed with #335

**Closed** 2020-01-05 21:07 UTC

**Comment by Duvel** [comment] 2020-01-05 21:27
Cool, are you going to do another release? I was about to flash another pi this week and could test the new release and flash tool.

**Comment by StefanScherer** [comment] 2020-01-06 11:13
There is a pre-release 1.12.0-rc2 right now where we could need some feedback.

**Comment by Duvel** [comment] 2020-01-06 21:20
I ran some test-runs and was able to break docker-compose again. But I found out that this was due to uninstalling cloud-init, which removes a few needed packages.

Can you add the packages python3-yaml and python3-jsonschema to the image? It appears that is what is needed for docker-compose.

Is there anything else that needs to be tested in this release?
